services:
  - type: web
    name: long-bio-bot
    runtime: python
    plan: free
    region: singapore
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
